"diff --git a/tensorflow/python/kernel_tests/random/random_gamma_test.py b/tensorflow/python/kernel_tests/random/random_gamma_test.py\nindex 71b06da183f..4d3ea4fe528 100644\n--- a/tensorflow/python/kernel_tests/random/random_gamma_test.py\n+++ b/tensorflow/python/kernel_tests/random/random_gamma_test.py\n@@ -16,7 +16,10 @@\n \n import numpy as np\n \n+from tensorflow.python.eager import context\n+from tensorflow.python.framework import constant_op\n from tensorflow.python.framework import dtypes\n+from tensorflow.python.framework import errors\n from tensorflow.python.framework import ops\n from tensorflow.python.framework import random_seed\n from tensorflow.python.framework import test_util\n@@ -216,6 +219,16 @@ class RandomGammaTest(test.TestCase):\n         self.assertEqual(0, math_ops.reduce_sum(math_ops.cast(\n             math_ops.less_equal(x, 0.), dtype=dtypes.int64)).eval())\n \n+  def testSizeTooLarge(self):\n+    # Grappler asserts on size overflow, so this error is only caught when\n+    # running eagerly.\n+    if context.executing_eagerly():\n+      with self.assertRaisesRegex((ValueError, errors.InvalidArgumentError),\n+                                  \"overflow\"):\n+        rate = constant_op.constant(1.0, shape=(4, 4, 4, 4, 4))\n+        self.evaluate(\n+            random_ops.random_gamma(\n+                shape=[46902, 51188, 34063, 59195], alpha=rate))\n \n if __name__ == \"__main__\":\n   test.main()"